version: 2.1

parameters:
  wp_theme_name:
    type: string
    default: busmagique
  wp_folder:
    type: string
    default: applications/$APP_SYS_USR/public_html

executors:
  node-executor:
    docker:
      - image: cimg/node:19.3.0

commands:
  setup-ssh:
    description: Setup SSH for server connexion
    parameters:
      host:
        type: env_var_name
        default: SERVER_HOST
    steps:
      - run:
          name: Install sshpass and rsync
          command: |
            sudo apt update
            sudo apt install sshpass rsync

      - run:
          name: Add server ip to known hosts
          command: |
            ssh-keyscan ${<< parameters.host >>} >> ~/.ssh/known_hosts

  build-theme:
    description: Fetch and build default theme
    steps:
      - run:
          name: Build theme
          command: |
            npm install
            npm run prod

  deploy-theme:
    description: Send theme to Staging server
    parameters:
      host:
        type: env_var_name
        default: SERVER_HOST
      username:
        type: env_var_name
        default: SERVER_USERNAME
      password:
        type: env_var_name
        default: SERVER_PASSWORD
      wp_folder:
        type: string
        default: << pipeline.parameters.wp_folder >>
      wp_theme_name:
        type: string
        default: << pipeline.parameters.wp_theme_name >>

    steps:
      - run:
          name: Copy theme to server
          command: |
            source .circleci/.env
            sshpass -p ${<< parameters.password >>} rsync -av -e ssh --exclude='.circleci' --exclude='.git' . ${<< parameters.username >>}@${<< parameters.host >>}:<< parameters.wp_folder >>/wp-content/themes/<< parameters.wp_theme_name >>

  # As to deploy throug a specific job, because OVH server doesnt support SSH (so we have to use LFTP through SFTP)
  deploy-theme-prod:
    description: Send theme to Production server
    parameters:
      wp_theme_name:
        type: string
        default: << pipeline.parameters.wp_theme_name >>

    steps:
      - run:
          name: Install LFTP
          command: |
            sudo apt update
            sudo apt install lftp
      - run:
          name: Copy theme to server
          command: |
            lftp ftp://${PROD_SERVER_USERNAME}:${PROD_SERVER_PASSWORD}@${PROD_SERVER_HOST} -e "mirror -e -R -x .circleci -x .git . www/wp-content/themes/<< parameters.wp_theme_name >> ; quit"

jobs:
  deploy-staging:
    description: Deploy on staging server
    executor: node-executor
    resource_class: small
    steps:
      - checkout
      - setup-ssh
      # - build-theme
      - deploy-theme

  deploy-prod:
    description: Deploy on production server
    executor: node-executor
    resource_class: small
    steps:
      - checkout
      # - build-theme
      - deploy-theme-prod

workflows:
  staging:
    jobs:
      - deploy-staging:
          context: dev
          filters:
            branches:
              only:
                - develop

  production:
    jobs:
      - deploy-prod:
          context: dev
          filters:
            branches:
              only:
                - main
# VS Code Extension Version: 1.5.1
