name: Deploy on SEOPress Environment
run-name: "${{ github.actor }} is deploying on seopress environment 🚢"
on:
  push:
    branches:
      - staging

jobs:
  deploy-theme:
    name: "Deploy on seopress server"
    runs-on: ubuntu-latest
    env:
      THEME_PATH: /home/lebusmagiquelille.seopress.host/public_html/wp-content/themes/busmagique
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SEOPRESS_SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SEOPRESS_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Pull latest code and install dependencies
        run: |
          ssh ${{ secrets.SEOPRESS_SSH_USERNAME }}@${{ secrets.SEOPRESS_SSH_HOST }} "\
            cd $THEME_PATH && \
            sudo GIT_SSH_COMMAND='ssh -i /home/ubuntu/.ssh/id_ed25519 -o StrictHostKeyChecking=no' git fetch origin staging && \
            sudo git reset --hard origin/staging && \
            sudo composer install --optimize-autoloader --no-interaction"
